```{r}
# this script uses GDGT integration results to calculate GDGT-based indices and ratios. The script will calculate and run several bias-indicating indexes, identify outliers in your data based on these indices and eventually presents the SST and MAT results with outliers removed. 

#For this script to run smoothly, you should construct your excel input as follows: 
#1. Use the first sheet of your excel spreadsheet as your datasheet. It doesn't matter how many other sheets you have in that, as long as the leftmost contains your GDGT data.
#2. Name the columns at least by the following items (CAPsensitive, but not necessarily in this order): age; 1302; 1300; 1298; 1296; 1292; 1292'; 1050-1; 1050-2; 1036-1; 1036-2; 1034-1; 1034-2; 1032-1; 1032-2; 1022; 1020; 1018; 1050-tot; 1036-tot; 1034-tot; H-1034tot; 1032-tot.
#3. the '####-tot' are sums of the 5th and 6th methylated brGDGTs of that m/z, and one for the H-1034 brGMGTs. You should ask excel to calculate those for you.
#4. If you have not separated out the 5th and 6th methylated brGDGTs in the m/z 1050, 1036, 1034, 1032 (e.g., because you used the single-column chromatography on HPLC), add your peak areas to 1050-tot, 1036-tot, 1034-tot and 1032-tot. 
#5. When you have not analyzed certain elements in your entire dataframe, add NA, or leave those cells blank. When you have analyzed it and it was not in there, add 0 for those components.
#6. the script below assumes you have ages for your samples. If you only have depths for your data, you should replace `age` in all code in this script with `depth`, and have the column in your dataframe read 'depth'.
#7. Place your dataset into the "RGDGT" zipfile you just opened. Make sure your excel datafile has a ".xlsx" extension. Place the "RGDGT" folder on your desktop. 

#this runs all required packages. Make sure you have installed these packages first. 
library(caTools)
library(ggplot2)
library(dplyr)
library(readr)
library(readxl)
library(tidyverse)
library(plotly)

#opens datafiles. Enter the file name of your data below, at the xxxx. 
OGdata <- read_excel("~/Desktop/RGDGT/1172 OG.xlsx")
#This excel file contains the modern soil database from De Jonge et al., 2014 and Dearing Crampton-Flood et al., 2020, the peat data from Naafs et al., 2017 and various modern brGDGT datasets from rivers, coastal sediments and marine transects in Zell et al., 2014; Sinnighe Damste, 2016, Warden et al., 2018, Warden et al., 2016, De Jonge et al., 2015, Dearing Crampton-Flood et al., 2019
SOILdata <- read_excel("~/Desktop/RGDGT/soil data.xlsx")
#This excelfile contains Paleogene brGDGT datasets, from lignites, and marine sediments. Obtained from Hollis et al., 2019 (excluding the data from ODP Site 1172) and Willard et al., 2019
paleobr <- read_excel("~/Desktop/RGDGT/paleobr.xlsx")

#shows data tables below. Your data will be in `OGdata`.
SOILdata
paleobr
OGdata

```

```{r}
#this string of code adds columns to your dataframe with ratio calculations from your GDGT peak areas
OGdata <- OGdata %>% 
        mutate(
#some sums
          `SUM.ISO` = `1302` + `1300` + `1298` + `1296` + `1292` + `1292'`,
          `SUM.BR` = `1022` + `1020` + `1018` + `1036-tot` + `1034-tot` + `1032-tot` + `1050-tot`, 
          `SUM.ALL` = SUM.ISO + SUM.BR,
#fractional abundances for a total picture
          `F1302.ALL` = `1302` / SUM.ALL,
          `F1300.ALL` = `1300`/ SUM.ALL,
          `F1298.ALL` = `1298` / SUM.ALL,
          `F1296.ALL` = `1296` / SUM.ALL,
          `F1292.ALL` = `1292` / SUM.ALL,
          `F1292'.ALL` = `1292'` / SUM.ALL,
          `F1050-tot.ALL` = `1050-tot` / SUM.ALL,
          `F1036-tot.ALL` = `1036-tot` / SUM.ALL,
          `F1034-tot.ALL` = `1034-tot` / SUM.ALL,
          `F1032-tot.ALL` = `1032-tot` / SUM.ALL,
          `F1022.ALL` = `1022` / SUM.ALL,
          `F1020.ALL` = `1020` / SUM.ALL,
          `F1018.ALL` = `1018` / SUM.ALL,
#some fractional abundances of isoGDGTs for the Ring index
          `F1302.ISO` = `1302` / SUM.ISO,
          `F1300.ISO` = `1300` / SUM.ISO,
          `F1298.ISO` = `1298` / SUM.ISO,
          `F1296.ISO` = `1296` / SUM.ISO,
          `F1292.ISO` = `1292` / SUM.ISO,
          `F1292'.ISO` = `1292'` / SUM.ISO,
# fractional abundance for the brGDGTs
          `FR.TETR` = (`1022` + `1020` + `1018`) / SUM.BR,
          `FR.PEN` = (`1036-tot` + `1034-tot` + `1032-tot`) / SUM.BR,
          `FR.HEX` = (`1050-tot`) / SUM.BR,
#the TEX86 index        
          `TEX86` = (`1298` + `1296` + `1292'`)/(`1300` + `1298` + `1296` + `1292'`),
#depth contribution (Taylor et al., 2013) AOM (Weijers et al., 2011), lake in situ production (Blaga et al., 2009), methanogenic (Zhang et al.) and regio-isomer (O'brien et al., 2017) indices and the RING index
          `GDGT2/GDGT3` = `1298`/ `1296`, 
          `GDGT2/cren` = `1298` / `1292`,
          `GDGT0/cren` = `1302` / `1292`, 
          `Methzhang` = (`1300` + `1298` + `1296`) / (`1300` + `1298` + `1296` + `1292` + `1292'`),
          `fcren` = `1292'` / (`1292'` + `1292`),
          `RING` = F1300.ISO + 2*F1298.ISO + 3*F1296.ISO + 4*F1292.ISO + 4*`F1292'.ISO`,
          `RITEX` = (-0.77*TEX86) + (3.32*TEX86^2) + 1.59,
          `CAPRI` = abs(RITEX - RING),
#SST calibration (Kim et al., 2010)
          `SSTK10` = 68.4*(log10(TEX86)) + 38.6,
#and the linear calibration of O'Brien et al. (2017)
          `SSTOBL` = 58.8*TEX86 - 11.18,
#then the BIT index of Hopmans et al. (2004)
          `BIT` = (`1050-tot` + `1036-tot` + `1022`)/(`1292` + `1050-tot` + `1036-tot` + `1022`),
#then some branched GDGT ratios
          `NoRINGS` = (`1020` + `1034-1` + `1034-2` + 2*(`1018` + `1032-1` + `1032-2`))/(`1022` + `1020` + `1018` +        `1036-tot` + `1034-tot` + `1032-tot`),
          `NoRINGStetra` = (`1020` + (2*`1018`)) / (`1022` + `1020` + `1018`),
          `NoRINGSpenta` = (`1034-tot` + 2*`1032-tot`)/(`1036-tot` + `1034-tot` + `1032-tot`),
          `NoRINGSpenta5` = (`1034-1` + 2*`1032-1`) / (`1036-1` + `1034-1` + `1032-1`),
          `NoRINGSpenta6` = (`1034-2` + 2*`1032-2`) / (`1036-2` + `1034-2` + `1032-2`),
          `IRpenta` = (`1036-2` + `1034-2` + `1032-2`) / (`1036-tot` + `1034-tot` + `1032-tot`),
          `IRhexa` = `1050-2` / `1050-tot`,
#DeJonge2014  (MBT'5ME = MBT5ME, because 1048 and 1046 were not integrated)
          `IR` = (`1032-2` + `1034-2` + `1036-2` + `1050-2`)/(`1050-tot` + `1036-tot` + `1034-tot` + `1032-tot`),
          `MBT5ME` = (`1022` + `1020` + `1018`) / (`1022` + `1020` + `1018` + `1036-1` + `1034-1` + `1032-1` + `1050-1`),
          `CBT'` = (`1018` + `1032-2` + `1034-2` + `1036-2` + `1050-2`) / (`1050-1` + `1036-1` + `1022`),
          `pH` = 7.15 + 1.59 * `CBT'`,
          `MAT5ME` = -8.57 + 31.45 * MBT5ME,
#Naafs et al., 2017
          `CBTpeat` = log10((`1020` + `1036-2` + `1034-tot` + `1050-2`)/(`1022` + `1036-1` + `1050-1`)),
          `MAATPEAT` = 52.18 * `MBT5ME` - 23.05,
          `PHPEAT` = 2.49 * CBTpeat + 8.07,
#deltaSST-MAT
          dT = SSTOBL - MAT5ME,
              )

# this shows the plot with the new indices added as columns
OGdata

```

```{r}
# this adds oulier rules for TEX86. 
#If: 
#RING outside CAPDELRI curves, 
#GDGT2/GDGT3 > 5 OR, 
#GDGT2/cren > 0.2 OR, 
#GDGT0/cren > 2 OR,
#Methzhang > 0.3  
#TEX86 is overprinted by non-thermal signals, or nonpelagic isoGDGTs 
#BIT index values are a problematic outlier criterium, for the values are too ambiguous to serve as flag for potential overprints, and interpretation strongly depend on the depositional setting. In proximal marine settings, high BIT index values could indicate contributions from terrestrially-sourced isoGDGTs, but in offshore settings, not. We recommend to look whether the samples with high BIT also have anomalous RING index values, or other overprints.  

#The code below adds columns to your dataframe with a logical value (TRUE or FALSE) for each outlier rule. The final OUTLIER column is added with a logical value for whether any of the other oulier rule is true
OGdata <- OGdata %>% 
        mutate(
                `outlierBIT` = BIT > 0.4,
                `outlierfcren` = `fcren` > 0.25,
                `outlierGDGT2/3` = `GDGT2/GDGT3` > 5, 
                `outlierGDGT2/cren` = `GDGT2/cren` > 0.2, 
                `outlierGDGT0/cren` = `GDGT0/cren` > 2,
                `outlierMethzhang` = `Methzhang` > 0.3,
                `outlierCAPRI` = CAPRI > 0.3,
                `OUTLIERTEX` = `outlierGDGT2/3` | `outlierGDGT0/cren` | `outlierMethzhang` | outlierCAPRI | outlierfcren
                )

#and outlier values for reconstruction of soil-based MAT. High IR values are generally suspicious for river-produced GDGTs (De Jonge et al., 2014), and high values of the number of rings is generally a measure for marine in-situ production (Sinninghe Damste 2016; Dearing Crampton-Flood et al., 2019).
OGdata <- OGdata %>%
      mutate(
              `outlierIR` = IR>0.5,
              `outlierNoRINGS` = NoRINGStetra>0.75 & NoRINGSpenta>0.75,
              `OUTLIERMBT` = outlierIR | outlierNoRINGS
              )

# and this shows the new columns
OGdata

```

```{r}
#This sets a plotting theme, to make the plots look slightly nicer than the standard in GGplot. if you modify this theme, the changes will be consistenly applied to all figures
Theme1 <- theme(
                panel.background = element_rect(fill = NA, color = "black"),
                plot.background = element_rect(fill = NA),
                panel.grid = element_blank()
                )

```

```{r}
#now for some plots! First look at the relative abundance of GDGTs:
dat1 <- select(OGdata, age, `F1302.ALL`:`F1018.ALL`)
dat1 <- pivot_longer(dat1, `F1302.ALL`:`F1018.ALL`, values_to = "fraction", names_to = "biomarker")
dat1
 ggplot(dat1)+
      geom_area(mapping = aes(x = age, y = fraction, fill = biomarker))+
      scale_fill_manual(values = c("#003300", "#336633", "#009933", "#66CC33", "#66FF00", "#CCFF99", "#CCFFCC", "#000033", "#003366", "#003399", "#0033CC", "#3366FF", "#0099FF"))+
   Theme1
 
 #removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("1. GDGTcomposition.pdf")
```


```{r}
#Here we evaluate whether the composition of isoGDGTs follows that of normal modern pelagic isoGDGTs
# ring index and TEX86 values in the modern isoGDGTs forllow the black regression line, with 2 sigma confidence intervals indicated with the grey lines. CAPdeltaRingindex >0.3 is defined to approach the 2 sigma confidence intervals of the modern dataset. Anything outside that is influenced by non-thermal GDGT contributions. 

#these are the outer bounds of the ring index, outside which samples should be discarded
RITEX.U <-  function(TEX86) (-0.39*TEX86) + (2.98*TEX86^2) + 1.79
RITEX.L <-  function(TEX86) (-1.15*TEX86) + (3.66*TEX86^2) + 1.39

ggplot() +
        geom_point(OGdata, mapping = aes(x = TEX86, y = RING, color = `age`, shape = `OUTLIERTEX`)) +
        scale_shape_manual(values = c(16, 4)) + 
        scale_color_gradient(trans = 'reverse')+
        geom_line(OGdata, mapping = aes(x = TEX86, y = RITEX.L(TEX86)), color = "grey") + 
        geom_line(OGdata, mapping = aes(x = TEX86, y = RITEX.U(TEX86)), color = "grey")+
        geom_line(OGdata, mapping = aes(x = TEX86, y = RITEX))+
        scale_x_continuous(limits = c(0.35, 0.85), breaks = seq(0.3, 0.9, 0.1))+
        scale_y_continuous(limits = c(0,3.5), breaks = seq(0, 3.5, 0.5))+
        Theme1

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("2. RINGindex.pdf")

```

```{r}
# then plot the outliers based on other indices, and the an overview of al outliers. I hope you see very few red crosses! 

dat2 <- select(OGdata, age, `outlierBIT`, `outlierGDGT2/3`, `outlierGDGT0/cren`, `outlierGDGT2/cren`, `outlierMethzhang`, outlierCAPRI, TEX86, fcren, BIT, `GDGT2/GDGT3`, `GDGT2/cren`, `GDGT0/cren`, `Methzhang`, CAPRI)

`dat2.BIT` <- select(dat2, age, `BIT`, `outlierBIT`)
`dat2.BITF` <- filter(dat2.BIT, outlierBIT == FALSE)
`dat2.BITT` <- filter(dat2.BIT, outlierBIT == TRUE)

`dat2.2/3` <- select(dat2, age, `GDGT2/GDGT3`, `outlierGDGT2/3`)
`dat2.2/3F` <- filter(`dat2.2/3`, `outlierGDGT2/3` ==FALSE)
`dat2.2/3T` <- filter(`dat2.2/3`, `outlierGDGT2/3` ==TRUE)

`dat2.0/cren` <- select(dat2, age, `GDGT0/cren`, `outlierGDGT0/cren`)
`dat2.0/crenF` <- filter(`dat2.0/cren`, `outlierGDGT0/cren` == FALSE)
`dat2.0/crenT` <- filter(`dat2.0/cren`, `outlierGDGT0/cren` == TRUE)

`dat2.2/cren` <- select(dat2, age, `GDGT2/cren`, `outlierGDGT2/cren`)
`dat2.2/crenF` <- filter(`dat2.2/cren`, `outlierGDGT2/cren` == FALSE)
`dat2.2/crenT` <- filter(`dat2.2/cren`, `outlierGDGT2/cren` == TRUE)

`dat2.Methzhang` <- select(dat2, age, `Methzhang`, `outlierMethzhang`)
`dat2.MethzhangF` <- filter(`dat2.Methzhang`, `outlierMethzhang` == FALSE)
`dat2.MethzhangT` <- filter(`dat2.Methzhang`, `outlierMethzhang` == TRUE)

`dat2.CAPRI` <- select(dat2, age, `CAPRI`, `outlierCAPRI`)
`dat2.CAPRIF` <- filter(dat2.CAPRI, outlierCAPRI == FALSE)
`dat2.CAPRIT` <- filter(dat2.CAPRI, outlierCAPRI == TRUE)

`dat2.TEX86` <- select(dat2, age, TEX86)
`dat2.fcren` <- select(dat2, age, fcren)

`dat2.BITF` <- pivot_longer(dat2.BITF, outlierBIT, names_to = "INDICE", values_to = "Result")
`dat2.2/3F` <- pivot_longer(`dat2.2/3F`, `outlierGDGT2/3`, names_to = "INDICE", values_to = "Result")
`dat2.0/crenF` <- pivot_longer(`dat2.0/crenF`, `outlierGDGT0/cren`, names_to = "INDICE", values_to = "Result")
`dat2.2/crenF` <- pivot_longer(`dat2.2/crenF`, `outlierGDGT2/cren`, names_to = "INDICE", values_to = "Result")
`dat2.0/MethzhangF` <- pivot_longer(`dat2.MethzhangF`, `outlierMethzhang`, names_to = "INDICE", values_to = "Result")
`dat2.CAPRIF` <- pivot_longer(dat2.CAPRIF, outlierCAPRI, names_to = "INDICE", values_to = "Result")

`dat2.BITT` <- pivot_longer(`dat2.BITT`, `outlierBIT`, names_to = "INDICE", values_to = "Result")
`dat2.2/3T` <- pivot_longer(`dat2.2/3T`, `outlierGDGT2/3`, names_to = "INDICE", values_to = "Result")
`dat2.0/crenT` <- pivot_longer(`dat2.0/crenT`, `outlierGDGT0/cren`, names_to = "INDICE", values_to = "Result")
`dat2.2/crenT` <- pivot_longer(`dat2.2/crenT`, `outlierGDGT2/cren`, names_to = "INDICE", values_to = "Result")
`dat2.0/MethzhangT` <- pivot_longer(`dat2.MethzhangT`, `outlierMethzhang`, names_to = "INDICE", values_to = "Result")
`dat2.CAPRIT` <- pivot_longer(`dat2.CAPRIT`, `outlierCAPRI`, names_to = "INDICE", values_to = "Result")


dat2.T <- bind_rows(dat2.BITT, `dat2.2/3T`, `dat2.0/crenT`, `dat2.2/crenT`, `dat2.0/MethzhangT`, dat2.CAPRIT)
dat2.F <- bind_rows(dat2.BITF, `dat2.2/3F`, `dat2.0/crenF`, `dat2.2/crenF`, `dat2.0/MethzhangF`, dat2.CAPRIF, dat2.TEX86, dat2.fcren)

dat2.T <- pivot_longer(dat2.T, cols=c(BIT, `GDGT2/GDGT3`, `GDGT2/cren`, `GDGT0/cren`, `Methzhang`, CAPRI), names_to = "key", values_to = "value")
dat2.F <- pivot_longer(dat2.F, cols=c(TEX86, BIT, fcren, `GDGT2/GDGT3`, `GDGT2/cren`, `GDGT0/cren`, `Methzhang`, CAPRI), names_to = "key", values_to = "value")


dat2.a <- data.frame("facet_label" = c("c. fcren (O'Brien et al., 2017)", "b. BIT index (Hopmans et al., 2004)", "f. Water column overprint (Taylor et al., 2013)", "e. AOM index (Weijers et al., 2011)", "g. Methanogenesis (Blaga et al., 2009)", "d. Methane index (Zhang et al., 2011)", "h. CAPRI (Zhang et al., 2016)"), "value" = c(0.25, 0.4, 5, 0.2, 2, 0.3, 0.3))
dat2.b <- data.frame("facet_label" = "a. TEX86 (Schouten et al., 2002)", "value" = c(0.72))

dat2.T$key_f = factor(dat2.T$key, levels = c("BIT", "Methzhang", "GDGT2/cren", "GDGT2/GDGT3", "GDGT0/cren", "CAPRI"))
dat2.F$key_f = factor(dat2.F$key, levels = c("TEX86", "BIT", "fcren", "Methzhang", "GDGT2/cren", "GDGT2/GDGT3", "GDGT0/cren", "CAPRI"))

dat2.T <- mutate(dat2.T, facet_label = fct_recode(
        key_f, 
        "b. BIT index (Hopmans et al., 2004)" = "BIT", 
        "d. Methane index (Zhang et al., 2011)" = "Methzhang", 
        "e. AOM index (Weijers et al., 2011)" = "GDGT2/cren", 
        "f. Water column overprint (Taylor et al., 2013)" = "GDGT2/GDGT3", 
        "g. Methanogenesis (Blaga et al., 2009)" = "GDGT0/cren",
        "h. CAPRI (Zhang et al., 2016)" = "CAPRI"
    ))

dat2.F <- mutate(dat2.F, facet_label = fct_recode(
        key_f, 
        "a. TEX86 (Schouten et al., 2002)" = "TEX86",
        "c. fcren (O'Brien et al., 2017)" = "fcren",
        "b. BIT index (Hopmans et al., 2004)" = "BIT", 
        "d. Methane index (Zhang et al., 2011)" = "Methzhang", 
        "e. AOM index (Weijers et al., 2011)" = "GDGT2/cren", 
        "f. Water column overprint (Taylor et al., 2013)" = "GDGT2/GDGT3", 
        "g. Methanogenesis (Blaga et al., 2009)" = "GDGT0/cren",
        "h. CAPRI (Zhang et al., 2016)" = "CAPRI"
    ))

ggplot()+
        geom_point(dat2.F, mapping = aes(x = age, y = value), size = 0.1) +
        geom_point(dat2.T, mapping = aes(x = age, y = value), size = 0.6, shape = 4, color = "red") +
        geom_hline(dat2.a, mapping = aes(yintercept = value), colour = "red")+
        geom_hline(dat2.b, mapping = aes(yintercept = value), colour = "blue")+
        facet_grid(facet_label~., scales = "free") +
        labs(x = "Age (Ma)", y = "index value")+
        Theme1 + 
        theme(strip.text.y = element_text(angle=0, size = 7, hjust = 0), 
              aspect.ratio = 0.3,
              plot.title = element_text(size = 7),
              axis.title = element_text(size = 7),
              axis.text = element_text(size = 5)) 

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("3. IsoGDGToverprints.pdf")
```


```{r}
#SSTs with biased samples removed. 

#first, data selection and transformation
dat3 <- select(OGdata, age, SSTK10, SSTOBL, OUTLIERTEX)
dat3.G <- filter(dat3, !OUTLIERTEX)
dat3.O <- filter(dat3, OUTLIERTEX)
dat3.Gr <- pivot_longer(dat3.G, cols=c(SSTOBL, SSTK10), names_to = "Calibration", values_to = "sea surface temperature")
dat3.Or <- pivot_longer(dat3.O, cols=c(SSTOBL, SSTK10), names_to = "Calibration", values_to = "sea surface temperature")

# then visualization
ggplot()+
        geom_line(dat3.Gr, mapping = aes(x = `age`, y = `sea surface temperature`, color = Calibration))+
        geom_point(dat3.Gr, mapping = aes(x = `age`, y = `sea surface temperature`, color = Calibration, shape = Calibration))+
        geom_point (dat3.Or, mapping = aes(x = `age`, y = `sea surface temperature`, color = Calibration), shape = 4)+
        scale_color_manual(values = c("grey", "black"))+
        scale_shape_manual(values = c(15, 16))+
        Theme1+
        labs(x = "Age (Ma)", y = "Sea surface temperature (Celsius)")

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("4. TEX86SST.pdf")

```



```{r}
# and some cross-plots for IR indices and number of rings.

#data selection
dat5.SOIL <- select(SOILdata, location, substrate, type, NoRINGStetra, NoRINGSpenta, NoRINGSpenta5, NoRINGSpenta6, IRpenta, IRhexa)
dat5.paleo <- select(paleobr, location, substrate, type, NoRINGStetra, NoRINGSpenta, NoRINGSpenta5, NoRINGSpenta6, IRpenta, IRhexa)
dat5 <- select(OGdata, NoRINGStetra, NoRINGSpenta, NoRINGSpenta5, NoRINGSpenta6, IR, IRpenta, IRhexa)

#combining the dataframes, and ordering them
dat5a <- bind_rows(dat5.SOIL, dat5.paleo)
dat5a$location_8f = factor(dat5a$location, levels = c("Global soil", "Global peat", "Amazon", "Baltic", "Berau", "Portugal", "Svalbard", "Siberia", "ACEX", "Otway", "Harrell", "mid-waipara", "U1356", "Cobham", "Otaio", "India", "Schoeningen"))

#data visualization
ggplot()+
      geom_point(dat5a, mapping = aes(x = NoRINGStetra, y = NoRINGSpenta, color = substrate, shape = location_8f))+
      scale_shape_manual(values = c(3, 4, 0, 1, 2, 5, 6, 7, 15, 16, 17, 18, 20, 15, 16, 17, 18))+
      geom_point(dat5, mapping = aes(x = NoRINGStetra, y = NoRINGSpenta), color = "black", shape = 4)+
      labs(x = "#Ringstetra", y = "#Ringspenta")+
      scale_x_continuous(limits = c(0,1), breaks = seq(0, 1, 0.2))+
      scale_y_continuous(limits = c(0,1), breaks = seq(0, 1, 0.2))+
      Theme1

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("5a. brGDGTcross.pdf")

ggplot()+
    geom_point(dat5a, mapping = aes(x = NoRINGStetra, y = NoRINGSpenta5, color = substrate, shape = location_8f))+
    scale_shape_manual(values = c(3, 4, 0, 1, 2, 5, 6, 7, 15, 16, 17, 18, 15, 16, 17, 18, 19))+
    geom_point(dat5, mapping = aes(x = NoRINGStetra, y = NoRINGSpenta5), color = "black", shape = 4)+
    labs(x = "#Ringstetra", y = "#Ringspenta5")+
    scale_x_continuous(limits = c(0,1), breaks = seq(0, 1, 0.2))+
    scale_y_continuous(limits = c(0,1), breaks = seq(0, 1, 0.2))+
    Theme1

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("5b. brGDGTcross.pdf")

ggplot()+
    geom_point(dat5a, mapping = aes(x = NoRINGStetra, y = NoRINGSpenta6, color = substrate, shape = location_8f))+
    scale_shape_manual(values = c(3, 4, 0, 1, 2, 5, 6, 7, 15, 16, 17, 18, 15, 16, 17, 18, 19))+
    geom_point(dat5, mapping = aes(x = NoRINGStetra, y = NoRINGSpenta6), color = "black", shape = 4)+
    labs(x = "#Ringstetra", y = "#Ringspenta6")+
    scale_x_continuous(limits = c(0,1), breaks = seq(0, 1, 0.2))+
    scale_y_continuous(limits = c(0,1), breaks = seq(0, 1, 0.2))+
    Theme1

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("5c. brGDGTcross.pdf")

ggplot()+
    geom_point(dat5a, mapping = aes(x = IRpenta, y = IRhexa, color = substrate, shape = location_8f))+
    scale_shape_manual(values = c(3, 4, 0, 1, 2, 5, 6, 7, 15, 16, 17, 18, 15, 16, 17, 18, 19))+
    geom_point(dat5, mapping = aes(x = IRpenta, y = IRhexa), shape = 4)+
    labs(x = "IRpenta", y = "IRhexa")+
    scale_x_continuous(limits = c(0,1), breaks = seq(0, 1, 0.2))+
    scale_y_continuous(limits = c(0,1), breaks = seq(0, 1, 0.2))+
    Theme1

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("5d. brGDGTcross.pdf")

```



```{r}
# time series of overprints on the brGDGTs

#data selection and filtering
dat6 <- select(OGdata, age, "BIT", "IR", "NoRINGStetra")
dat6 <- mutate(dat6, "OUTLIERIR" = IR>0.5)
dat6 <- pivot_longer(dat6, cols=c(BIT, IR, NoRINGStetra), names_to = "TYPE", values_to = "index")
dat6 <- filter(dat6, index>0)
dat6.T <- filter(dat6, !OUTLIERIR)
dat6.F <- filter(dat6, OUTLIERIR)
dat6.F <- filter(dat6.F, TYPE == "IR")
dat6a <- data.frame("TYPE" = c("IR", "NoRINGStetra"), "value" = c(0.5, 0.75))

#and the visualization
ggplot()+
        geom_point(dat6.T, mapping = aes(x = age, y = index), size = 0.3) +
        geom_line(dat6.T, mapping = aes(x = age, y = index)) +
        geom_hline(dat6a, mapping = aes(yintercept = value), color = "red")+
        geom_point(dat6.F, mapping = aes(x = age, y = index), shape = 4, color = "red", size = 0.3)+
        facet_grid(TYPE~., scales = "free")+
        labs(x = "Age (Ma)", y = "index")+
        Theme1 + 
        theme(strip.text.y = element_text(angle=0, size = 7), 
              aspect.ratio = 0.3,
              plot.title = element_text(size = 7),
              axis.title = element_text(size = 7),
              axis.text = element_text(size = 7))

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("6. brGDGTindices.pdf")

```

```{r}
# Fig. 9. MAT data plotted with the calibrations
#data gathering
dat7 <- select(OGdata, age, MBT5ME, OUTLIERMBT, `MAT5ME`, `MAATPEAT`, `IR`)

dat7r <- pivot_longer(dat7, cols=c(`MAT5ME`: MAATPEAT), names_to = "TYPE", values_to = "Temp")
dat7.G <- filter(dat7r, !OUTLIERMBT)
dat7.G <- filter(dat7.G, MBT5ME<1.0)
dat7.O <- filter(dat7r, OUTLIERMBT)


ggplot()+
        geom_point(dat7.G, mapping = aes(x = age, y = Temp, colour = TYPE), size = 0.4) +
        geom_line(dat7.G, mapping = aes(x = age, y = Temp, colour = TYPE)) +
        geom_point(dat7.O, mapping = aes(x = age, y = Temp, colour = TYPE), shape = 4, size = 0.4)+
        scale_color_manual(values = c("dark grey", "light grey", "black"))+
        labs(x = "Age(Ma)", y = "Air temperature (celsius)", size = 7) +
        Theme1+
        theme(aspect.ratio = 0.7, 
              legend.position = c(0.4, 0.3),
              legend.text = element_text(size=7),
              legend.title = element_text(size = 9)
              )

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("7. MAATcalibrations.pdf")
```

```{r}
#alright! ready for some data plots with the overprinted data removed? Here we go! 

#data gathering and transformation
dat8s <- select(dat3.G, age, SSTOBL)
dat8m <- select(dat7, age, MBT5ME, MAT5ME, OUTLIERMBT)
dat8m <- filter(dat8m, !OUTLIERMBT, MBT5ME<1.0)
dat8sa <- pivot_longer(dat8s, SSTOBL, names_to = "Type", values_to = "Temp")
dat8ma <- pivot_longer(dat8m, MAT5ME, names_to = "Type", values_to = "Temp")
dat8 <- bind_rows(dat8sa, dat8ma)

#data visualization
ggplot(dat8, mapping = aes(x = age, y = Temp))+
        geom_point(aes(colour = Type), size  = 0.4)+
        geom_line(aes(colour = Type))+
        scale_color_manual(values = c("dark green", "blue"))+
        labs(x = "Age (Ma)", y = "Temperature (Celsius)")+
        coord_fixed(0.8)+
        theme(legend.position = c(0.15, 0.8), legend.title = element_blank())+
        Theme1

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("8. SST_MAAT.pdf")

#and a crossplot between SST and MAT, with only those samples that have non-overprinted SST and MAT values
dat9 <- inner_join(dat8s, dat8m)
dat9.1 <- filter(dat9, age>56.0)
dat9.2 <- filter(dat9, age<56.0 & age>55.85)
dat9.3 <- filter(dat9, age<55.85 & age>40.0)
dat9.4 <- filter(dat9, age<40.0 & age>39.5)
dat9.5 <- filter(dat9, age<39.5)

dat9f <- bind_rows(dat9.1, dat9.3, dat9.5)


ggplot() +
        geom_point(dat9f, mapping = aes(x = MAT5ME, y = SSTOBL, color = `age`)) +
  geom_point(dat9.2, mapping = aes(x = MAT5ME, y = SSTOBL, color = age), shape = 15)+
  geom_point(dat9.4, mapping = aes(x = MAT5ME, y = SSTOBL, color = age), shape = 17)+
        scale_color_gradient(trans = 'reverse')+
        Theme1

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 #ggsave("9. SST_MAATcross.pdf")
```

