```{r}
# this script uses iso- and brGDGT integration results to calculate isoGDGT-based indices and ratios. The script will calculate and run several bias-indicating indexes, identify outliers in your data based on these indices and eventually presents the SST results with outliers removed. 

#For this script to run smoothly, you should construct your excel input as follows: 
#1. Use the first sheet of your excel spreadsheet as your datasheet. It doesn't matter how many other sheets you have in that, as long as the leftmost contains your GDGT data.
#2. Name the columns at least by the following items (CAPsensitive, but not necessarily in this order): age; 1302; 1300; 1298; 1296; 1292; 1292'; 1050-tot; 1036-tot; 1022.
#3. the ####-tot are sums of the 5th and 6th methylated brGDGTs of that m/z, if you have separated those out. You should ask excel to calculate those for you.
#4. If you have not separated out the 5th and 6th methylated brGDGTs in the m/z 1050 and 1036, (e.g., because you used the single-column chromatography on HPLC), add your peak areas to 1050-tot, 1036-tot. 
#5. When you have not analyzed certain elements in your entire dataframe, add NA, or leave those cells blank. When you have analyzed it and it was not in there, add 0 for those components.
#6. the script below assumes you have ages for your samples. If you only have depths for your data, you should replace `age` in all code in this script with `depth`, and have the column in your dataframe read 'depth'.
#7. Place your dataset into the "RGDGT" zipfile you just opened. Make sure your excel datafile has a ".xlsx" extension. Place the "RGDGT" folder on your desktop. 

#this runs all required packages. Make sure you have installed these packages first. 
library(caTools)
library(ggplot2)
library(dplyr)
library(readr)
library(readxl)
library(tidyverse)
library(plotly)

#opens datafiles. Enter the file name of your data below, at the xxxx. 
OGdata <- read_excel("~/Desktop/RGDGT/1172 OG.xlsx")
#This excel file contains the modern soil database from De Jonge et al., 2014 and Dearing Crampton-Flood et al., 2020, the peat data from Naafs et al., 2017 and various modern brGDGT datasets from rivers, coastal sediments and marine transects in Zell et al., 2014; Sinnighe Damste, 2016, Warden et al., 2018, Warden et al., 2016, De Jonge et al., 2015, Dearing Crampton-Flood et al., 2019

#shows your data frame below.
OGdata

```

```{r}
OGdata <- OGdata %>% 
        mutate(
#some sums
          `SUM.ISO` = `1302` + `1300` + `1298` + `1296` + `1292` + `1292'`,
          `SUM.BR` = `1022` + `1036-tot` + `1050-tot`, 
          `SUM.ALL` = SUM.ISO + SUM.BR,
#fractional abundances for a total picture
          `F1302.ALL` = `1302` / SUM.ALL,
          `F1300.ALL` = `1300`/ SUM.ALL,
          `F1298.ALL` = `1298` / SUM.ALL,
          `F1296.ALL` = `1296` / SUM.ALL,
          `F1292.ALL` = `1292` / SUM.ALL,
          `F1292'.ALL` = `1292'` / SUM.ALL,
          `F1050-tot.ALL` = `1050-tot` / SUM.ALL,
          `F1036-tot.ALL` = `1036-tot` / SUM.ALL,
          `F1022.ALL` = `1022` / SUM.ALL,
#some fractional abundances of isoGDGTs for the Ring index
          `F1302.ISO` = `1302` / SUM.ISO,
          `F1300.ISO` = `1300` / SUM.ISO,
          `F1298.ISO` = `1298` / SUM.ISO,
          `F1296.ISO` = `1296` / SUM.ISO,
          `F1292.ISO` = `1292` / SUM.ISO,
          `F1292'.ISO` = `1292'` / SUM.ISO,
# fractional abundance for the brGDGTs
          `FR.TETR` = (`1022`) / SUM.BR,
          `FR.PEN` = (`1036-tot`) / SUM.BR,
          `FR.HEX` = (`1050-tot`) / SUM.BR,
#the TEX86 index        
          `TEX86` = (`1298` + `1296` + `1292'`)/(`1300` + `1298` + `1296` + `1292'`),
#depth contribution (Taylor et al., 2013) AOM (Weijers et al., 2011), lake in situ production (Blaga et al., 2009), methanogenic (Zhang et al.) and regio-isomer (O'brien et al., 2017) indices and the RING index
          `GDGT2/GDGT3` = `1298`/ `1296`, 
          `GDGT2/cren` = `1298` / `1292`,
          `GDGT0/cren` = `1302` / `1292`, 
          `Methzhang` = (`1300` + `1298` + `1296`) / (`1300` + `1298` + `1296` + `1292` + `1292'`),
          `fcren` = `1292'` / (`1292'` + `1292`),
          `RING` = F1300.ISO + 2*F1298.ISO + 3*F1296.ISO + 4*F1292.ISO + 4*`F1292'.ISO`,
          `RITEX` = (-0.77*TEX86) + (3.32*TEX86^2) + 1.59,
          `CAPRI` = abs(RITEX - RING),
#SST calibration (Kim et al., 2010)
          `SSTK10` = 68.4*(log10(TEX86)) + 38.6,
#and the linear calibration of O'Brien et al. (2017)
          `SSTOBL` = 58.8*TEX86 - 11.18,
#then the BIT index of Hopmans et al. (2004)
          `BIT` = (`1050-tot` + `1036-tot` + `1022`)/(`1292` + `1050-tot` + `1036-tot` + `1022`),
)

# this shows the plot with the new indices added as columns
OGdata
```

```{r}
# this adds oulier rules for TEX86. 
#If: 
#RING outside CAPDELRI curves, 
#GDGT2/GDGT3 > 5 OR, 
#GDGT2/cren > 0.2 OR, 
#GDGT0/cren > 2 OR,
#Methzhang > 0.3  
#TEX86 is overprinted by non-thermal signals, or nonpelagic isoGDGTs 
#BIT index values are a problematic outlier criterium, for the values are too ambiguous to serve as flag for potential overprints, and interpretation strongly depend on the depositional setting. In proximal marine settings, high BIT index values could indicate contributions from terrestrially-sourced isoGDGTs, but in offshore settings, not. We recommend to look whether the samples with high BIT also have anomalous RING index values, or other overprints.  

#The code below adds columns to your dataframe with a logical value (TRUE or FALSE) for each outlier rule. The final OUTLIER column is added with a logical value for whether any of the other oulier rule is true
OGdata <- OGdata %>% 
        mutate(
                `outlierBIT` = BIT > 0.4,
                `outlierfcren` = `fcren` > 0.25,
                `outlierGDGT2/3` = `GDGT2/GDGT3` > 5, 
                `outlierGDGT2/cren` = `GDGT2/cren` > 0.2, 
                `outlierGDGT0/cren` = `GDGT0/cren` > 2,
                `outlierMethzhang` = `Methzhang` > 0.3,
                `outlierCAPRI` = CAPRI > 0.3,
                `OUTLIERTEX` = `outlierGDGT2/3` | `outlierGDGT0/cren` | `outlierMethzhang` | outlierCAPRI | outlierfcren
                )


# and this shows the new columns
OGdata
```

```{r}
#This sets a plotting theme, to make the plots look slightly nicer than the standard in GGplot. if you modify this theme, the changes will be consistenly applied to all figures
Theme1 <- ggplot2::theme(
                panel.background = element_rect(fill = NA, color = "black"),
                plot.background = element_rect(fill = NA),
                panel.grid = element_blank()
                )
```

```{r}
#now for some plots! First look at the relative abundance of GDGTs and GMGTs
dat1 <- select(OGdata, age, `F1302.ALL`:`F1022.ALL`)
dat1 <- gather(dat1, `F1302.ALL`:`F1022.ALL`, value = "fraction", key = "biomarker")
dat1
 ggplot(dat1)+
      geom_area(mapping = aes(x = age, y = fraction, fill = biomarker))+
      scale_fill_manual(values = c("#336633", "#009933", "#CCFFCC", "#000033", "#003366", "#003399", "#0033CC", "#3366FF", "#0099FF"))+
   Theme1
 
 #removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 ggsave("1. GDGTcomposition.pdf")
```

```{r}
#Here we evaluate whether the composition of isoGDGTs follows that of normal modern pelagic isoGDGTs
# ring index and TEX86 values in the modern isoGDGTs forllow the black regression line, with 2 sigma confidence intervals indicated with the grey lines. CAPdeltaRingindex >0.3 is defined to approach the 2 sigma confidence intervals of the modern dataset. Anything outside that is influenced by non-thermal GDGT contributions. 

#these are the outer bounds of the ring index, outside which samples should be discarded
RITEX.U <-  function(TEX86) (-0.39*TEX86) + (2.98*TEX86^2) + 1.79
RITEX.L <-  function(TEX86) (-1.15*TEX86) + (3.66*TEX86^2) + 1.39

ggplot() +
        geom_point(OGdata, mapping = aes(x = TEX86, y = RING, color = `age`, shape = `OUTLIERTEX`)) +
        scale_shape_manual(values = c(16, 4)) + 
        scale_color_gradient(trans = 'reverse')+
        geom_line(OGdata, mapping = aes(x = TEX86, y = RITEX.L(TEX86)), color = "grey") + 
        geom_line(OGdata, mapping = aes(x = TEX86, y = RITEX.U(TEX86)), color = "grey")+
        geom_line(OGdata, mapping = aes(x = TEX86, y = RITEX))+
  scale_x_continuous(limits = c(0.35, 0.85), breaks = seq(0.3, 0.9, 0.1))+
  scale_y_continuous(limits = c(0,3.5), breaks = seq(0, 3.5, 0.5))+
        Theme1

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 ggsave("2. RINGindex.pdf")
```

```{r}
# then plot the outliers based on other indices, and the an overview of al outliers. I hope you see very few red crosses! 

dat2 <- select(OGdata, age, `outlierBIT`, `outlierGDGT2/3`, `outlierGDGT0/cren`, `outlierGDGT2/cren`, `outlierMethzhang`, outlierCAPRI, TEX86, fcren, BIT, `GDGT2/GDGT3`, `GDGT2/cren`, `GDGT0/cren`, `Methzhang`, CAPRI)

`dat2.BIT` <- select(dat2, age, `BIT`, `outlierBIT`)
`dat2.BITF` <- filter(dat2.BIT, outlierBIT == FALSE)
`dat2.BITT` <- filter(dat2.BIT, outlierBIT == TRUE)

`dat2.2/3` <- select(dat2, age, `GDGT2/GDGT3`, `outlierGDGT2/3`)
`dat2.2/3F` <- filter(`dat2.2/3`, `outlierGDGT2/3` ==FALSE)
`dat2.2/3T` <- filter(`dat2.2/3`, `outlierGDGT2/3` ==TRUE)

`dat2.0/cren` <- select(dat2, age, `GDGT0/cren`, `outlierGDGT0/cren`)
`dat2.0/crenF` <- filter(`dat2.0/cren`, `outlierGDGT0/cren` ==FALSE)
`dat2.0/crenT` <- filter(`dat2.0/cren`, `outlierGDGT0/cren` ==TRUE)

`dat2.2/cren` <- select(dat2, age, `GDGT2/cren`, `outlierGDGT2/cren`)
`dat2.2/crenF` <- filter(`dat2.2/cren`, `outlierGDGT2/cren` ==FALSE)
`dat2.2/crenT` <- filter(`dat2.2/cren`, `outlierGDGT2/cren` ==TRUE)

`dat2.Methzhang` <- select(dat2, age, `Methzhang`, `outlierMethzhang`)
`dat2.MethzhangF` <- filter(`dat2.Methzhang`, `outlierMethzhang` ==FALSE)
`dat2.MethzhangT` <- filter(`dat2.Methzhang`, `outlierMethzhang` ==TRUE)

`dat2.CAPRI` <- select(dat2, age, `CAPRI`, `outlierCAPRI`)
`dat2.CAPRIF` <- filter(dat2.CAPRI, outlierCAPRI == FALSE)
`dat2.CAPRIT` <- filter(dat2.CAPRI, outlierCAPRI == TRUE)

`dat2.TEX86` <- select(dat2, age, TEX86)
`dat2.fcren` <- select(dat2, age, fcren)

`dat2.BITF` <- gather(dat2.BITF, outlierBIT, key = INDICE, value = Result)
`dat2.2/3F` <- gather(`dat2.2/3F`, `outlierGDGT2/3`, key = INDICE, value = Result)
`dat2.0/crenF` <- gather(`dat2.0/crenF`, `outlierGDGT0/cren`, key = INDICE, value = Result)
`dat2.2/crenF` <- gather(`dat2.2/crenF`, `outlierGDGT2/cren`, key = INDICE, value = Result)
`dat2.0/MethzhangF` <- gather(`dat2.MethzhangF`, `outlierMethzhang`, key = INDICE, value = Result)
`dat2.CAPRIF` <- gather(dat2.CAPRIF, outlierCAPRI, key = INDICE, value = Result)

`dat2.BITT` <- gather(`dat2.BITT`, `outlierBIT`, key = INDICE, value = Result)
`dat2.2/3T` <- gather(`dat2.2/3T`, `outlierGDGT2/3`, key = INDICE, value = Result)
`dat2.0/crenT` <- gather(`dat2.0/crenT`, `outlierGDGT0/cren`, key = INDICE, value = Result)
`dat2.2/crenT` <- gather(`dat2.2/crenT`, `outlierGDGT2/cren`, key = INDICE, value = Result)
`dat2.0/MethzhangT` <- gather(`dat2.MethzhangT`, `outlierMethzhang`, key = INDICE, value = Result)
`dat2.CAPRIT` <- gather(`dat2.CAPRIT`, `outlierCAPRI`, key = INDICE, value = Result)


dat2.T <- bind_rows(dat2.BITT, `dat2.2/3T`, `dat2.0/crenT`, `dat2.2/crenT`, `dat2.0/MethzhangT`, dat2.CAPRIT)
dat2.F <- bind_rows(dat2.BITF, `dat2.2/3F`, `dat2.0/crenF`, `dat2.2/crenF`, `dat2.0/MethzhangF`, dat2.CAPRIF, dat2.TEX86, dat2.fcren)

dat2.T <- gather(dat2.T, BIT, `GDGT2/GDGT3`, `GDGT2/cren`, `GDGT0/cren`, `Methzhang`, CAPRI, key = "key", value = "value")
dat2.F <- gather(dat2.F, TEX86, BIT, fcren, `GDGT2/GDGT3`, `GDGT2/cren`, `GDGT0/cren`, `Methzhang`, CAPRI, key = "key", value = "value")


dat2.a <- data.frame("facet_label" = c("c. fcren (O'Brien et al., 2017)", "b. BIT index (Hopmans et al., 2004)", "f. Water column overprint (Taylor et al., 2013)", "e. AOM index (Weijers et al., 2011)", "g. Methanogenesis (Blaga et al., 2009)", "d. Methane index (Zhang et al., 2011)", "h. CAPRI (Zhang et al., 2016)"), "value" = c(0.25, 0.4, 5, 0.2, 2, 0.3, 0.3))
dat2.b <- data.frame("facet_label" = "a. TEX86 (Schouten et al., 2002)", "value" = c(0.72))

dat2.T$key_f = factor(dat2.T$key, levels = c("BIT", "Methzhang", "GDGT2/cren", "GDGT2/GDGT3", "GDGT0/cren", "CAPRI"))
dat2.F$key_f = factor(dat2.F$key, levels = c("TEX86", "BIT", "fcren", "Methzhang", "GDGT2/cren", "GDGT2/GDGT3", "GDGT0/cren", "CAPRI"))

dat2.T <- mutate(dat2.T, facet_label = fct_recode(
        key_f, 
        "b. BIT index (Hopmans et al., 2004)" = "BIT", 
        "d. Methane index (Zhang et al., 2011)" = "Methzhang", 
        "e. AOM index (Weijers et al., 2011)" = "GDGT2/cren", 
        "f. Water column overprint (Taylor et al., 2013)" = "GDGT2/GDGT3", 
        "g. Methanogenesis (Blaga et al., 2009)" = "GDGT0/cren",
        "h. CAPRI (Zhang et al., 2016)" = "CAPRI"
    ))

dat2.F <- mutate(dat2.F, facet_label = fct_recode(
        key_f, 
        "a. TEX86 (Schouten et al., 2002)" = "TEX86",
        "c. fcren (O'Brien et al., 2017)" = "fcren",
        "b. BIT index (Hopmans et al., 2004)" = "BIT", 
        "d. Methane index (Zhang et al., 2011)" = "Methzhang", 
        "e. AOM index (Weijers et al., 2011)" = "GDGT2/cren", 
        "f. Water column overprint (Taylor et al., 2013)" = "GDGT2/GDGT3", 
        "g. Methanogenesis (Blaga et al., 2009)" = "GDGT0/cren",
        "h. CAPRI (Zhang et al., 2016)" = "CAPRI"
    ))

ggplot()+
        geom_point(dat2.F, mapping = aes(x = age, y = value), size = 0.1) +
        geom_point(dat2.T, mapping = aes(x = age, y = value), size = 0.6, shape = 4, color = "red") +
        geom_hline(dat2.a, mapping = aes(yintercept = value), colour = "red")+
        geom_hline(dat2.b, mapping = aes(yintercept = value), colour = "blue")+
        facet_grid(facet_label~., scales = "free") +
        labs(x = "Age (Ma)", y = "index value")+
        Theme1 + 
        theme(strip.text.y = element_text(angle=0, size = 7, hjust = 0), 
              aspect.ratio = 0.3,
              plot.title = element_text(size = 7),
              axis.title = element_text(size = 7),
              axis.text = element_text(size = 5)) 

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 ggsave("3. IsoGDGToverprints.pdf")
```

```{r}
#SSTs with biased samples removed. 

#first, data selection and transformation
dat3 <- select(OGdata, age, SSTK10, SSTOBL, OUTLIERTEX)
dat3.G <- filter(dat3, !OUTLIERTEX)
dat3.O <- filter(dat3, OUTLIERTEX)
dat3.Gr <- gather(dat3.G, SSTOBL, SSTK10, key = "Calibration", value = "sea surface temperature")
dat3.Or <- gather(dat3.O, SSTOBL, SSTK10, key = "Calibration", value = "sea surface temperature")

# then visualization
ggplot()+
        geom_line(dat3.Gr, mapping = aes(x = `age`, y = `sea surface temperature`, color = Calibration))+
        geom_point(dat3.Gr, mapping = aes(x = `age`, y = `sea surface temperature`, color = Calibration, shape = Calibration))+
        geom_point (dat3.Or, mapping = aes(x = `age`, y = `sea surface temperature`, color = Calibration), shape = 4)+
        scale_color_manual(values = c("grey", "black"))+
        scale_shape_manual(values = c(15, 16))+
        Theme1+
        labs(x = "Age (Ma)", y = "Sea surface temperature (Celsius)")

#removing the `#` in the command line below saves this figure as PDF in your RGDGT folder
 ggsave("4. TEX86SST.pdf")

```

